sonar.projectKey=Tranloi2k_Nova-shop-monorepo
sonar.organization=tranloi2k
sonar.sourceEncoding=UTF-8
sonar.javascript.lcov.reportPaths=Nova-online-shopping-nextjs/coverage/lcov.info,Nova-admin/coverage/lcov.info,Nova-shop-Nestjs/coverage/lcov.info
