sonar.projectKey=Tranloi2k_Nova-shop-monorepo
sonar.organization=tranloi2k
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.tests=.
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**,**/coverage/**,**/*.spec.ts,**/*.spec.tsx,**/*.test.ts,**/*.test.tsx
sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx,**/*.test.ts,**/*.test.tsx
sonar.coverage.exclusions=**/*.spec.ts,**/*.spec.tsx,**/*.test.ts,**/*.test.tsx
sonar.javascript.lcov.reportPaths=Nova-online-shopping-nextjs/coverage/lcov.info,Nova-admin/coverage/lcov.info,Nova-shop-Nestjs/coverage/lcov.info
sonar.cpd.exclusions=**/*.spec.ts,**/*.spec.tsx,**/*.test.ts,**/*.test.tsx
